export const space = {
  0: "0px",
  1: "1px",
  2: "2px",
  3: "4px",
  4: "6px",
  5: "8px",
  6: "12px",
  7: "16px",
  8: "20px",
  9: "24px",
  10: "30px",
  11: "32px",
  12: "38px",
  13: "40px",
};

export const fontSize = {
  heroLarge: "34px",
  heroMedium: "28px",
  heroSmall: "24px",
  titleLarge: "22px",
  titleMedium: "20px",
  titleSmall: "18px",
  headingLarge: "18px",
  headingMedium: "16px",
  headingSmall: "14px",
  bodyStrongLarge: "16px",
  bodyStrongMedium: "14px",
  bodyStrongSmall: "13px",
  bodyEmpLarge: "16px",
  bodyEmpMedium: "14px",
  bodyEmpSmall: "13px",
  bodyLarge: "16px",
  bodyMedium: "14px",
  bodySmall: "13px",
  buttonLarge: "16px",
  buttonMedium: "14px",
  buttonSmall: "13px",
  captionLarge: "13px",
  captionMedium: "12px",
  captionSmall: "11px",
};

export const borderRadius = {
  1: "2px",
  2: "4px",
  3: "6px",
  4: "8px",
};

export const fontFamily = {
  body: "Inter var, sans-serif",
};

export const lineHeight = {
  heroLarge: "40px",
  heroMedium: "36px",
  heroSmall: "30px",
  titleLarge: "28px",
  titleMedium: "26px",
  titleSmall: "24px",
  headingLarge: "24px",
  headingMedium: "22px",
  headingSmall: "18px",
  bodyStrongLarge: "24px",
  bodyStrongMedium: "22px",
  bodyStrongSmall: "20px",
  bodyEmpLarge: "24px",
  bodyEmpMedium: "22px",
  bodyEmpSmall: "20px",
  bodyLarge: "24px",
  bodyMedium: "22px",
  bodySmall: "20px",
  buttonLarge: "24px",
  buttonMedium: "22px",
  buttonSmall: "20px",
  captionLarge: "20px",
  captionMedium: "18px",
  captionSmall: "16px",
};

export const fontVariationWeight = {
  heroLarge: '"wght" 580',
  heroMedium: '"wght" 580',
  heroSmall: '"wght" 500',
  titleLarge: '"wght" 380',
  titleMedium: '"wght" 380',
  titleSmall: '"wght" 380',
  headingLarge: '"wght" 600',
  headingMedium: '"wght" 600',
  headingSmall: '"wght" 600',
  bodyStrongLarge: '"wght" 600',
  bodyStrongMedium: '"wght" 600',
  bodyStrongSmall: '"wght" 600',
  bodyEmpLarge: '"wght" 500',
  bodyEmpMedium: '"wght" 500',
  bodyEmpSmall: '"wght" 500',
  bodyLarge: '"wght" 440',
  bodyMedium: '"wght" 440',
  bodySmall: '"wght" 440',
  buttonLarge: '"wght" 580',
  buttonMedium: '"wght" 580',
  buttonSmall: '"wght" 580',
  captionLarge: '"wght" 380',
  captionMedium: '"wght" 440',
  captionSmall: '"wght" 480',
};

export const letterSpacing = {
  heroLarge: "-0.01em",
  heroMedium: "-0.01em",
  heroSmall: "-0.01em",
  titleLarge: "normal",
  titleMedium: "normal",
  titleSmall: "normal",
  headingLarge: "normal",
  headingMedium: "normal",
  headingSmall: "0.01em",
  bodyStrongLarge: "0.01em",
  bodyStrongMedium: "0.01em",
  bodyStrongSmall: "0.015em",
  bodyEmpLarge: "0.01em",
  bodyEmpMedium: "0.01em",
  bodyEmpSmall: "0.015em",
  bodyLarge: "0.01em",
  bodyMedium: "0.01em",
  bodySmall: "0.015em",
  buttonLarge: "0.02em",
  buttonMedium: "0.02em",
  buttonSmall: "0.025em",
  captionLarge: "0.01em",
  captionMedium: "0.015em",
  captionSmall: "0.025em",
};

export const borderWidth = {
  0: "0px",
  1: "1px",
};
