import {
  borderRadius,
  borderWidth,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  spacing,
} from "./common";

export const defaultDark = {
  spacing,
  colors: {
    background: {
      accent1: "null",
      buttonDefaultPrimary: "null",
      buttonDefaultSecondary: "null",
      buttonDefaultTertiary: "null",
      critical1: "null",
      critical2: "null",
      default1: "null",
      default2: "null",
      default3: "null",
      defaultDisabled: "null",
      info1: "null",
      info2: "null",
      success1: "null",
      success2: "null",
      warning1: "null",
      warning2: "null",
    },
    text: {
      accent1: "null",
      buttonDefaultPrimary: "null",
      buttonDefaultSecondary: "null",
      buttonDefaultTertiary: "null",
      critical1: "null",
      default1: "null",
      default2: "null",
      default3: "null",
      defaultDisabled: "null",
      info1: "null",
      success1: "null",
      warning1: "null",
    },
    border: {
      accent1: "null",
      critical1: "null",
      default1: "null",
      default2: "null",
      default3: "null",
      defaultDisabled: "null",
      info1: "null",
      success1: "null",
      warning1: "null",
    },
  },
  fontSize,
  borderRadius,
  lineHeight,
  fontWeight,
  letterSpacing,
  boxShadow: {
    interactiveDefaultFocused: "0px 1px 1px 0px hsla(0, 0%, 0%, 0.32)",
    interactiveDefaultHovering: "0px 2px 3px 0px hsla(0, 0%, 0%, 0.28)",
    overlay: "0px 3px 8px 0px hsla(0, 0%, 0%, 0.24)",
    modal: "0px 8px 16px 0px hsla(0, 0%, 0%, 0.2)",
  },
  borderWidth,
};
