blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/saleor/macaw-ui/discussions
    about: If you have a support question or need help getting MacawUI to work, please use GitHub Discussions.
