name: Enhancement request
description: "Small scope enhancements that do not alter the behavior of the product: Spelling, text adjustments, documentation, small visual corrections, icon adjustments, etc."
title: "[Enhancement]: "
labels: ["enhancement", "backlog"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the enhancement
      description: Describe what you want to improve, attach the reasoning.
      placeholder: |
        Example: I want to adjust shade of the background token
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Attach some additional references, links, some context
      placeholder: |
        Example: Currently the default background token is too dark, we need more contrast.
    validations:
      required: false
