import { createSprinkles, defineProperties } from "@vanilla-extract/sprinkles";
import { vars } from "./contract.css";

const responsiveProperties = defineProperties({
  conditions: {
    mobile: {},
    tablet: { "@media": "screen and (min-width: 768px)" },
    desktop: { "@media": "screen and (min-width: 1024px)" },
  },
  defaultCondition: "mobile",
  properties: {
    display: ["none", "flex", "grid", "block"],
    flexDirection: ["row", "column"],
    alignItems: ["stretch", "flex-start", "center", "flex-end"],
    justifyContent: [
      "stretch",
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    flexGrow: ["0", "1"],
    flexShrink: ["0", "1"],
    flexBasis: ["auto", "0"],
    position: ["static", "relative", "absolute", "fixed", "sticky"],
    gridArea: ["auto"],
    gridTemplateAreas: ["none"],
    gridTemplateRows: ["repeat(2,1fr)", "repeat(3,1fr)"],
    gridTemplateColumns: ["repeat(2,1fr)", "repeat(3,1fr)"],
    flexWrap: ["nowrap", "wrap"],
    gap: vars.space,
    paddingTop: vars.space,
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    paddingRight: vars.space,
    marginTop: { ...vars.space, auto: "auto" },
    marginBottom: { ...vars.space, auto: "auto" },
    marginLeft: { ...vars.space, auto: "auto" },
    marginRight: { ...vars.space, auto: "auto" },
    width: { ...vars.space, "100%": "100%", "100vw": "100vw" },
    height: { ...vars.space, "100%": "100%", "100vh": "100vh" },
    minHeight: ["auto", "100%", "0px"],
    minWidth: ["auto", "100%", "0px"],
    maxWidth: ["auto", "100%", "0px"],
    maxHeight: ["auto", "100%", "0px"],
    borderTopRightRadius: { ...vars.borderRadius, "50%": "50%" },
    borderTopLeftRadius: { ...vars.borderRadius, "50%": "50%" },
    borderBottomRightRadius: { ...vars.borderRadius, "50%": "50%" },
    borderBottomLeftRadius: { ...vars.borderRadius, "50%": "50%" },
    fontFamily: vars.fontFamily,
    fontSize: vars.fontSize,
    lineHeight: vars.lineHeight,
    textAlign: ["center"],
    borderLeftWidth: vars.borderWidth,
    borderRightWidth: vars.borderWidth,
    borderTopWidth: vars.borderWidth,
    borderBottomWidth: vars.borderWidth,
    borderLeftStyle: ["none", "solid"],
    borderRightStyle: ["none", "solid"],
    borderTopStyle: ["none", "solid"],
    borderBottomStyle: ["none", "solid"],
    outlineStyle: ["none"],
    fontWeight: vars.fontWeight,
    textTransform: ["uppercase"],
    letterSpacing: vars.letterSpacing,
    top: vars.space,
    bottom: vars.space,
    left: vars.space,
    right: vars.space,
    overflowX: ["hidden", "visible", "scroll", "auto"],
    overflowY: ["hidden", "visible", "scroll", "auto"],
  },
  shorthands: {
    padding: ["paddingTop", "paddingBottom", "paddingLeft", "paddingRight"],
    paddingX: ["paddingLeft", "paddingRight"],
    paddingY: ["paddingTop", "paddingBottom"],
    margin: ["marginTop", "marginBottom", "marginLeft", "marginRight"],
    marginX: ["marginLeft", "marginRight"],
    marginY: ["marginTop", "marginBottom"],
    placeItems: ["alignItems", "justifyContent"],
    typeSize: ["fontSize", "lineHeight", "fontWeight", "letterSpacing"],
    borderWidth: [
      "borderTopWidth",
      "borderBottomWidth",
      "borderLeftWidth",
      "borderRightWidth",
    ],
    borderXWidth: ["borderLeftWidth", "borderRightWidth"],
    borderYWidth: ["borderTopWidth", "borderBottomWidth"],
    borderStyle: [
      "borderTopStyle",
      "borderBottomStyle",
      "borderLeftStyle",
      "borderRightStyle",
    ],
    borderXStyle: ["borderLeftStyle", "borderRightStyle"],
    borderYStyle: ["borderTopStyle", "borderBottomStyle"],
    inset: ["top", "bottom", "left", "right"],
    borderRadius: [
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    overflow: ["overflowX", "overflowY"],
    flex: ["flexGrow", "flexShrink", "flexBasis"],
  },
});

const stateProperties = defineProperties({
  conditions: {
    default: {},
    hover: { selector: "&:hover" },
    focus: { selector: "&:focus" },
    focusVisible: { selector: "&:focus-visible" },
    active: { selector: "&:active" },
    disabled: { selector: "&[disabled]" },
  },
  defaultCondition: "default",
  properties: {
    borderColor: vars.colors.border,
    color: { ...vars.colors.foreground, inherit: "inherit" },
    backgroundColor: vars.colors.background,
    pointerEvents: ["none", "auto"],
    cursor: ["pointer", "not-allowed", "auto"],
    boxShadow: vars.boxShadow,
  },
});

export const sprinkles = createSprinkles(responsiveProperties, stateProperties);

export type Sprinkles = Parameters<typeof sprinkles>[0];
