name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Run chromatic tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]
      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/canary'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/canary'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
